__base__: "general.yaml"
seed: 42
log:
  name: "defaultname"
  dir: "" # default save to /output/exp
  tensorboard_log_interval: 7  # Log losses every N steps

checkpoint:
  resume: true          # 是否从断点恢复
  resume_path: "/workspace/gan_seg/outputs/step_6000_b2_a1.pt"
  overwrite_flow_predictor: false
  overwrite_flow_path: "/workspace/epoch=23.ckpt"
  save_every_iters: 1000
model:
  flow:
    name: "FastFlow3D"
    lr: 2e-6
    FastFlow3D:
      VOXEL_SIZE: [0.2, 0.2, 6]
      PSEUDO_IMAGE_DIMS: [512, 512]
      POINT_CLOUD_RANGE: [-51.2, -51.2, -3, 51.2, 51.2, 3]
      FEATURE_CHANNELS: 32
      SEQUENCE_LENGTH: 2
  mask:
    name: "MaskFormer3D"
    lr: 1e-5
    weight_decay: 0.0
    slot_num: 16
    lr_decay: 0.7
    lr_decay_step: 8000
    lr_clip: 1e-7
    MaskFormer3D:
      n_point: 8192
      n_transformer_layer: 4
      transformer_embed_dim: 256
      transformer_input_pos_enc: False

dataset:
  name: "AV2_SceneFlowZoo"
  AV2_SceneFlowZoo:
    root_dir: "/workspace/av2data/train"
    subsequence_length: 2
    sliding_window_step_size: 1
    with_ground: false
    with_rgb: false
    eval_type: "bucketed_epe"
    expected_camera_shape: (194, 256, 3)
    cache_root: "/workspace/av2data/cache"
    use_gt_flow: false
    flow_data_path: "/workspace/av2flow/train/"
    min_instance_size: 50

  val_name: "AV2_SceneFlowZoo_val"
  AV2_SceneFlowZoo_val_flow:
    root_dir: "/workspace/av2data/val"
    with_ground: false
    with_rgb: false
    eval_type: "bucketed_epe"
    expected_camera_shape: (194, 256, 3)
    use_gt_flow: true
    cache_root: "/workspace/av2data/cache"
    flow_data_path: "/workspace/av2flow/val/"
    eval_args_output_path: "eval_results/bucketed_epe/nsfp_distillation_1x/"
  AV2_SceneFlowZoo_val_mask:
    root_dir: "/workspace/av2data/val"
    with_ground: false
    with_rgb: false
    eval_type: "bucketed_epe"
    expected_camera_shape: (194, 256, 3)
    use_gt_flow: false
    cache_root: "/workspace/av2data/cache"
    flow_data_path: "/workspace/av2flow/val/"
    eval_args_output_path: "eval_results/bucketed_epe/nsfp_distillation_1x/"
    min_instance_size: 50
lr_multi:
  rec_loss: 0
  flow_loss: 0.0
  scene_flow_smoothness: 0
  rec_flow_loss: 0.0
  point_smooth_loss: 0.0
  eular_flow_loss: 0.0
  KDTree_loss: 0
  KNN_loss: 5
  l1_regularization: 0.0
  eular_mask_loss: 0
  invariance_loss: 0.0
  scene_flow_smoothness_scheduler:
    begin_iter: 0
    end_iter: 8000
    begin_value: 1.0
    end_value: 1.0

alternate:
  flow: [[50,true],[50,true]]
  mask: [[50,false],[50,false]]
training:
  use_icp_inference_flow: false
  max_iter: 300000
  eval_loop: 500
  begin_train_smooth: 0
  begin_train_point_smooth: 0
  begin_train_flow: 0
  begin_train_mask: 1000000
  begin_train_invariance: 0
  mask_downsample_factor: 1
  grad_accumulation_steps: 1
  augment_params:
    angle_range: [-0.7, 0.7]
    translation_range: [1, 0,1]
    scale_range: [0.95, 1.05]
    mirror_x: true
    mirror_z: false
dataloader:
  batchsize: 2
  num_workers: 4
loss:
  scale_flow_magnitude: 10
  scene_flow_smoothness:
    square_mask: false
    scale_flow_grad: 0.1
    each_mask_item:
      relative_gradient: 1
      criterion: "L2"
    sum_mask_item:
      relative_gradient: 1
      criterion: "L2"
  point_smooth_loss:
    knn_loss_params:
      k: 32
      radius: 1
      loss_norm: 1
    ball_q_loss_params:
      k: 64
      radius: 2
      loss_norm: 1
  knn:
    ignore_ground: false
    k: 1
    reduction: "mean"
    distance_max_threshold: 2
    distance_min_threshold: 0.0
  reconstruction_loss:
    using_legend_loss: true
vis:
  show_window: false
  debug_grad: false

eval:
  eval_size: 300
  # eval_flow_size: 10
  eval_mask_size: 1
  min_points: 25
  ignore_class_ids: [-1,0]